runner:
  client:
    datadirs:
      besu:
        source_dir: ${STATE_DIR}/besu
        method: schelk
      geth:
        source_dir: ${STATE_DIR}/geth
        method: schelk
      nethermind:
        source_dir: ${STATE_DIR}/nethermind
        method: schelk
      reth:
        source_dir: ${STATE_DIR}/reth
        method: schelk
      erigon:
        source_dir: ${STATE_DIR}/erigon
        method: schelk
      ethrex:
        source_dir: ${STATE_DIR}/ethrex
        method: schelk
    config:
      genesis:
        nethermind: ${NETHERMIND_CHAINSPEC}
        ethrex: ${ETHREX_GENESIS}
        reth:  ${RETH_GENESIS}
        besu: ${BESU_GENESIS}
        erigon: ${ERIGON_GENESIS}
        geth: ${GETH_GENESIS}
