runner:
  client:
    datadirs:
      besu:
        source_dir: ${STATE_DIR}/besu
        method: schelk
      geth:
        source_dir: ${STATE_DIR}/geth
        method: schelk
      nethermind:
        source_dir: ${STATE_DIR}/nethermind
        method: schelk
      reth:
        source_dir: ${STATE_DIR}/reth
        method: schelk
      erigon:
        source_dir: ${STATE_DIR}/erigon
        method: schelk
      ethrex:
        source_dir: ${STATE_DIR}/ethrex
        method: schelk
    config:
      genesis:
        nethermind: ${STATE_DIR}/nethermind/parity-chainspec.json
        ethrex: ${STATE_DIR}/ethrex/ethrex-genesis.json
        reth:  ${STATE_DIR}/reth/chainspec.json
        besu: ${STATE_DIR}/besu/besu-chainspec.json
        # erigon: ${STATE_DIR}/erigon/chainspec.json
        ethrex: ${STATE_DIR}/ethrex/ethrex-genesis.json
